[iframe] Added geolocation field.
healthgovau/ask pull request #54
Opened 2021-05-27 02:05 UTC by Tjocksmurf

2021-05-27 03:33 UTC, Tjocksmurf commented
![](https://github.trello.services/images/mini-trello-icon.png) [iframe paragraph bundle (for hosted apps): add geolocation checkbox](https://trello.com/c/rg6C4fl2/373-iframe-paragraph-bundle-for-hosted-apps-add-geolocation-checkbox)

2021-05-28 07:00 UTC, Benjen requested changes
Overall looks good. I did a bit of a tidy up in the iframe paragraph template as there was some stuff I had implemented previously which I didn't like.

I am also not sure that 'off' is a valid option for the "allow" property. So changed it to specifically disable access to geolocation.

I think we should not have geolocation enabled by default (see comment for more info).

2021-05-28 07:00 UTC, Benjen commented on config/default/field.field.paragraph.para_h_content_iframe.field_h_allow_geolocation.yml
> +    value: 1
@Tjocksmurf - I can't see us needing to use this functionality very often other than in very specific use cases. I would suggest we leave it off by default given someone could embed anything in an iframe.

2021-05-31 03:04 UTC, Tjocksmurf commented on config/default/field.field.paragraph.para_h_content_iframe.field_h_allow_geolocation.yml
> +    value: 1
I've changed it to disabled by default

2021-06-02 06:19 UTC, Benjen approved these changes

2021-06-03 03:43 UTC, merged