[duplicate ids] Adjusted id and on this page script.
healthgovau/ask pull request #56
Opened 2021-05-28 03:17 UTC by Tjocksmurf

2021-06-01 05:17 UTC, Tjocksmurf commented
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicated H2 id's](https://trello.com/c/iV3GMtOX/523-duplicated-h2-ids)

2021-06-02 01:36 UTC, Benjen requested changes

2021-06-02 01:36 UTC, Benjen commented on themes/health/source/js/health.anchors.js
> +      //Ensure that we're not getting duplicates
@Tjocksmurf code comment should have space after "//" and end with "."

2021-06-02 01:36 UTC, Benjen commented on themes/health/source/js/health.anchors.js
> +          } else {
@Tjocksmurf "else" should be on new line.

2021-06-03 04:04 UTC, Benjen approved these changes

2021-06-03 05:00 UTC, merged