[content structure] Adjusted inline display
healthgovau/ask pull request #7
Opened 2021-03-17 00:38 UTC by Tjocksmurf

2021-03-17 02:01 UTC, Tjocksmurf commented
![](https://github.trello.services/images/mini-trello-icon.png) [Confirm structure of content displayed by Reference paragraphs](https://trello.com/c/7XUuvxvB/355-confirm-structure-of-content-displayed-by-reference-paragraphs)

2021-03-18 06:21 UTC, Benjen requested changes
Hi @Tjocksmurf ,

See comments for information on suggested changes.

2021-03-18 06:21 UTC, Benjen commented on config/default/core.entity_view_display.node.h_contact.h_inline.yml
>    field_h_contact_type:
Contact type should be removed from this display mode.

2021-03-18 06:21 UTC, Benjen commented on config/default/core.entity_view_display.node.h_publication.h_inline.yml
> +    label: above
Hide label

2021-03-18 06:21 UTC, Benjen commented on config/default/core.entity_view_display.node.h_publication.h_inline.yml
> +    weight: 2
Place between heading and summary.

2021-03-24 06:21 UTC, Benjen approved these changes

2021-03-24 06:39 UTC, merged